language: bash
sudo: required
dist: trusty
env:
- OS=debian ARCH=amd64 DIST=jessie
- OS=raspbian ARCH=armhf DIST=jessie
cache:
  directories:
  - "$HOME/cache"
before_install:
- wget --directory-prefix=/tmp https://raw.githubusercontent.com/ev3dev/ev3dev-buildscripts/master/pbuilder-ev3dev
- chmod +x /tmp/pbuilder-ev3dev
- "/tmp/pbuilder-ev3dev deps"
before_script:
- "/tmp/pbuilder-ev3dev base"
- git checkout -B ev3dev-$DIST
script:
- "/tmp/pbuilder-ev3dev build"
before_deploy:
- export LICENSES='"GPL-2.0"'
- if [ "$OS" == "debian" ]; then
    export DEB_ARCH="armel,armhf";
  fi
- "/tmp/pbuilder-ev3dev dpl"
deploy:
  on:
    tags: true
  provider: bintray
  file: "$HOME/bintray.json"
  user: dlech
  key:
    secure: 330L2KOWuBIiwJoMO9SFmekOoeyQ6kjT1UOdHnORVb0PCkr5d/3Je995eWqkZaiSYAl6Us0uGBtq8+hPR6iFLCiHMJFDGbbtsU7Qrj/ritMsJImHvjy6a9icGNU6+mIHOa3/TljHnPFPz25eOqiwRtvflv4pOffKO8RHU31hiUM=
